version: '3.4'

services:
  sqldb-catalog:
    container_name: sqldb-catalog
    restart: always
    volumes:
      - /c/data/docker/devinterview/sqlserver/catalog:/var/opt/mssql/data
    ports:
      - "1417:1433"
    environment:
      SA_PASSWORD: ".123Pass456."
      ACCEPT_EULA: "Y"

  svc-catalog:
    container_name: svc-catalog
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:CatalogDB:HostName=sqldb-catalog"
      - "ConnectionStrings:CatalogDB:Catalogue=Catalog"
      - "ConnectionStrings:CatalogDB:User=sa"
      - "ConnectionStrings:CatalogDB:Password=.123Pass456."
    ports:
      - "9010:80"
    depends_on:
      - sqldb-catalog
