version: '3.4'

services:
  sqldb-identity:
    image: mcr.microsoft.com/mssql/server

  sqldb-catalog:
    image: mcr.microsoft.com/mssql/server

  app-admin:
    image: ${DOCKER_REGISTRY-}app-admin
    build:
      context: .
      dockerfile: AdminPanel/DevInterview.AdminPanel.Web/Dockerfile

  agw-web:
    image: ${DOCKER_REGISTRY-}agw-web
    build:
      context: .
      dockerfile: WebApiGateway/Dockerfile

  svc-identity:
    image: ${DOCKER_REGISTRY-}svc-identity
    build:
      context: .
      dockerfile: Identity/DevInterview.Identity.Api/Dockerfile

  svc-catalog:
    image: ${DOCKER_REGISTRY-}svc-catalog
    build:
      context: .
      dockerfile: Catalog/DevInterview.Catalog.Api/Dockerfile



